name: Update pinned-gist
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  waka-box:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update waka-box
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: b5ad14812e80caebd892a98dbf5b8142
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

  productive-box:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update productive-box
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 01ea6249e8814b74f1c96bcaa8dc5ffa
          TIMEZONE: Asia/Seoul
